plugins:
  - jekyll-paginate

title: 'DevBlog'
url: "http://80.211.62.213"
permalink: /:categories/:title

sass:
  style: compressed

excerpt_separator: <!--more-->

paginate: 5
paginate_path: '/page-:num/'

socials:
  github: 'kaptn3'
  tlgrm: 'https://t.me/vikablog'
