plugins:
  - jekyll-paginate
  - jekyll-sitemap

title: 'Kapiko - блог о веб-разработке'
description: >
  "Kapiko - блог о веб-разработке. Здесь можно найти статьи по front-end и back-end разработке, а также администрированию сайтов."
url: "https://blog.kaptn.ru"
color: "#6767F6"
permalink: /:categories/:year/:title

sass:
  style: compressed

excerpt_separator: <!--more-->

paginate: 5
paginate_path: '/page/:num/'

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge

socials:
  github: 'kaptn3'
  tlgrm: 'https://t.me/kapiko_blog'
  disqus: 'devblog-9'

exclude: 
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
