plugins:
  - jekyll-paginate
  - jekyll-sitemap

title: 'DevBlog - блог о веб-разработке'
url: "https://blog.kaptn.ru"
color: "#6767F6"
permalink: /:categories/:title

sass:
  style: compressed

excerpt_separator: <!--more-->

paginate: 5
paginate_path: '/page/:num/'

socials:
  github: 'kaptn3'
  tlgrm: 'https://t.me/vikablog'
