import "../assets/css/globals.css"
import React from "react";
import {Metadata} from "next";
import {Header} from "@/components/Header";
import {Footer} from "@/components/Footer";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body suppressHydrationWarning={true} className="h-full flex justify-center bg-zinc-50 lg:px-8">
        <div className="w-full max-w-7xl lg:px-8">
          <div className="bg-white ring-1 ring-zinc-100">
            <Header />
            <div className="mx-auto max-w-2xl lg:max-w-5xl xl:relative px-4">
              <div className="mx-auto max-w-2xl">
                {children}
              </div>
            </div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
