import "../assets/css/globals.css"
import React from "react";
import {Header} from "@/components/Header";
import {Metadata} from "next";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body suppressHydrationWarning={true}>
        <Header />
        <div className="container w-full md:max-w-3xl mx-auto pt-20">
          <div className="w-full px-4 md:px-6 text-xl text-gray-800 leading-normal">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
